segmentation_filter_node:
  ros__parameters:
    input_topic: "/points/filtered"
    output_topic: "/patchworkpp/nonground"
    intensity: true
    vertical_zones:
      - "start: 0.1, end: 1.0, downsample: 1"
